In [218]:
import pandas as pd
import numpy as np

In [219]:
df_main = pd.read_csv('vacancies_tg_main.csv')
df_terms = pd.read_csv('vacancies_tg_terms.csv')
df_high = pd.read_csv('vacancies_tg_high_salary.csv')

In [220]:
df_main.head(5)

,channel,message_id,date,text,source
0,data_hr,1290,2026-04-09 09:36:02,LADA Цифра — дочерняя IT-компания АО «АВТОВАЗ»...,telegram
1,data_hr,1289,2026-04-07 11:22:32,🚀 Учись работать с реальными продуктовыми зада...,telegram
2,data_hr,1287,2026-04-03 13:25:54,#вакансия \n\nLead/Senior Data Scientist\n\nНа...,telegram
3,data_hr,1285,2026-03-24 08:57:38,#вакансия #разработчикDWH \n\nКомпания: Зонтик...,telegram
4,data_hr,1284,2026-03-20 09:49:22,#вакансия #аналитикданных\n🔎 Аналитик данных\n...,telegram

In [221]:
df_terms.head(5)

,channel,message_id,date,text,search_term,source
0,data_hr,1290,2026-04-09 09:36:02,LADA Цифра — дочерняя IT-компания АО «АВТОВАЗ»...,Python,telegram
1,data_hr,1289,2026-04-07 11:22:32,🚀 Учись работать с реальными продуктовыми зада...,Python,telegram
2,data_hr,1287,2026-04-03 13:25:54,#вакансия \n\nLead/Senior Data Scientist\n\nНа...,Python,telegram
3,data_hr,1284,2026-03-20 09:49:22,#вакансия #аналитикданных\n🔎 Аналитик данных\n...,Python,telegram
4,data_hr,1283,2026-03-20 07:34:07,Всем привет!\n\nКомпания: Большой зелёный банк...,Python,telegram

In [222]:
df_high.head(5)

,channel,message_id,date,text,source
0,data_hr,1250,2026-01-26 08:25:47,Data Never Lies is a UK-based data consultancy...,telegram
1,data_hr,1242,2026-01-13 12:33:26,Data Never Lies is a UK-based data consultancy...,telegram
2,data_hr,1236,2025-12-25 14:16:39,#вакансия\nПозиция: Дата-аналитик (Graph Analy...,telegram
3,data_hr,1164,2025-10-08 14:49:13,#Вакансия #аналитик #Product #Productanalyst #...,telegram
4,data_hr,1135,2025-09-04 08:37:09,#работа #удаленная_работа #вакансия #Team_Lead...,telegram

In [223]:
df_terms = df_terms.drop(columns=['search_term'])
df_terms

,channel,message_id,date,text,source
0,data_hr,1290,2026-04-09 09:36:02,LADA Цифра — дочерняя IT-компания АО «АВТОВАЗ»...,telegram
1,data_hr,1289,2026-04-07 11:22:32,🚀 Учись работать с реальными продуктовыми зада...,telegram
2,data_hr,1287,2026-04-03 13:25:54,#вакансия \n\nLead/Senior Data Scientist\n\nНа...,telegram
3,data_hr,1284,2026-03-20 09:49:22,#вакансия #аналитикданных\n🔎 Аналитик данных\n...,telegram
4,data_hr,1283,2026-03-20 07:34:07,Всем привет!\n\nКомпания: Большой зелёный банк...,telegram
...,...,...,...,...,...
7391,analysts_hunter,394837,2025-08-08 08:26:39,\#вакансия #systemanalyst #работа #hiring #job...,telegram
7392,analysts_hunter,394767,2025-08-07 12:21:24,#vacancy #вакансия\n\n💙 Компания: YADRO \n🔗 Ва...,telegram
7393,analysts_hunter,394677,2025-08-06 14:16:31,#вакансия #аналитика #работа #hiring #job #sen...,telegram
7394,analysts_hunter,394282,2025-08-05 10:59:59,#вакансия #SQL #работа #hiring #job #middle #s...,telegram
7395,analysts_hunter,394278,2025-08-05 09:49:15,#вакансия #SQL #работа #hiring #job #middle #s...,telegram

In [224]:
df_main['is_high_salary'] = False
df_terms['is_high_salary'] = False
df_high['is_high_salary'] = True

In [225]:
df_tg = pd.concat([df_main, df_terms, df_high], ignore_index=True)
df_tg

,channel,message_id,date,text,source,is_high_salary
0,data_hr,1290,2026-04-09 09:36:02,LADA Цифра — дочерняя IT-компания АО «АВТОВАЗ»...,telegram,False
1,data_hr,1289,2026-04-07 11:22:32,🚀 Учись работать с реальными продуктовыми зада...,telegram,False
2,data_hr,1287,2026-04-03 13:25:54,#вакансия \n\nLead/Senior Data Scientist\n\nНа...,telegram,False
3,data_hr,1285,2026-03-24 08:57:38,#вакансия #разработчикDWH \n\nКомпания: Зонтик...,telegram,False
4,data_hr,1284,2026-03-20 09:49:22,#вакансия #аналитикданных\n🔎 Аналитик данных\n...,telegram,False
...,...,...,...,...,...,...
25754,analysts_hunter,412921,2026-03-10 12:41:39,"День добрый. Ищу работу веб - аналитиком, CRM ...",telegram,True
25755,analysts_hunter,412742,2026-03-06 10:51:47,"Да ну достаточно на hh поиск запустить, чтобы ...",telegram,True
25756,analysts_hunter,412566,2026-03-05 14:28:42,#вакансия #product #owner #senior\nПозиция: Pr...,telegram,True
25757,analysts_hunter,411859,2026-02-25 08:36:08,Правила размещения вакансий в чате @analysts_h...,telegram,True
25758,analysts_hunter,411727,2026-02-22 19:41:43,Как вакансия меньше 600 к так мистеру лямбда м...,telegram,True

In [226]:
df_tg.isna().sum()

channel           0
message_id        0
date              0
text              0
source            0
is_high_salary    0
dtype: int64

Как и ожидалось, NaN у нас нет, это связано с тем, что сообщения не могут быть пустыми и не содержать что-то из полей выше.

In [227]:
len(df_tg)

25759

Сортируем, чтобы при дедупликации в выборе "есть пометка про з/п 400к+ или нет", удалились поля, не помеченные зп 400к+

In [228]:
df_tg = df_tg.sort_values('is_high_salary', ascending=False)
df_tg

,channel,message_id,date,text,source,is_high_salary
25758,analysts_hunter,411727,2026-02-22 19:41:43,Как вакансия меньше 600 к так мистеру лямбда м...,telegram,True
25160,devops_jobs_feed,20051,2025-02-10 09:09:31,Публикатор: Nelly🍒\nОбсуждение вакансии в чате...,telegram,True
25158,devops_jobs_feed,20076,2025-02-12 12:51:07,Публикатор: Анастасия Патрикеева\nОбсуждение в...,telegram,True
25157,devops_jobs_feed,20077,2025-02-12 12:51:35,Публикатор: Даниэлла Котовская🖤\nОбсуждение ва...,telegram,True
25156,devops_jobs_feed,20080,2025-02-12 17:08:23,Публикатор: Елизавета Бондарева 🌷\nОбсуждение ...,telegram,True
...,...,...,...,...,...,...
8584,python_jobs,231154,2025-08-15 16:18:37,это была синтаксическая ошибка,telegram,False
8583,python_jobs,231155,2025-08-15 16:18:51,душним до конца,telegram,False
8582,python_jobs,231156,2025-08-15 16:19:28,Оправдания такие оправдания,telegram,False
8581,python_jobs,231157,2025-08-15 16:20:01,Оправдания такие оправдания,telegram,False
12879,analysts_hunter,415193,2026-04-07 10:34:56,Выше правильно подсвечивали что есть зависимос...,telegram,False

In [229]:
df_tg = df_tg.drop_duplicates(subset=['channel', 'message_id'])

In [230]:
df_tg = df_tg.drop_duplicates(subset=['text'], keep='first').reset_index(drop=True)

In [231]:
len(df_tg)

17602

Дальше отфильтруем все короткие сообщения. Посмотрим распределение длин и увидим, что 25% всех сообщений короче 56 символов и это точно мусор. А средняя длина равна 877 символам, поэтому выберем порог в 200, чтобы отсечь явный мусор. Под мусором имеются в виду всякие служебные сообщения, уведомления и сообщения из чатов, тк там бывают обсуждения от обычных пользователей.

In [232]:
df_tg = df_tg[df_tg['text'].str.len() >= 200]

In [233]:
len(df_tg)

9503

Мы решили сфокусироваться на российском рынке, так что все вакансии с з/п в долларах, евро, фунтах и тд мы кикаем

In [234]:
foreign = df_tg['text'].str.contains(r'\$|£|€|USD|EUR|GBP', case=False, na=False)
df_tg = df_tg[~foreign]

In [235]:
len(df_tg)

7635

Дальше мы фильтруем каждый канал на сообщения с вакансиями. Во-первых, мы берем только вакансии с указанной з/п, потому что нам нужны конкретные цифры, это наша целевая переменная. Во-вторых, фильтруем по хештегам вакансий некоторые каналы, а именно делаем это на основе анализа типичных сообщений для каждого канала.   

python_jobs, devops_jobs_feed, analysts_hunter — тематические каналы, где все вакансии публикуются строго с хэштегом #вакансия. Остальные сообщения, то есть мусор, обсуждения, резюме, нам не нужны.   

data_hr — канал публикует как вакансии с хэштегом, так и вакансии без него.   

zrabota, vacancy_cs — в этих каналах вакансии публикуются без хэштегов.

In [236]:
channels = df_tg['channel']
hashtag_channels = ['python_jobs', 'devops_jobs_feed', 'analysts_hunter']

In [237]:
salary_pattern  = r'\d[\d\s]*[\.\s]\d{3}|\d{4,}|[1-9]\d{1,2}\s?[кkКK]|\d+\s?тыс'
vacancy_pattern = r'#вакансия|#vacancy|#job'
has_vacancy = df_tg['text'].str.contains(vacancy_pattern, case=False, na=False)
has_salary = df_tg['text'].str.contains(salary_pattern, case=False, na=False)

In [238]:
mask = ((~channels.isin(hashtag_channels) & has_salary) | (channels.isin(hashtag_channels) & has_vacancy & has_salary))
df_tg = df_tg[mask]

In [239]:
len(df_tg)

4423

In [240]:
df_tg['channel'].value_counts()

channel
devops_jobs_feed    2151
zrabota              772
data_hr              504
python_jobs          369
analysts_hunter      323
vacancy_cs           304
Name: count, dtype: int64

In [241]:
df_tg

,channel,message_id,date,text,source,is_high_salary
1,devops_jobs_feed,20051,2025-02-10 09:09:31,Публикатор: Nelly🍒\nОбсуждение вакансии в чате...,telegram,True
2,devops_jobs_feed,20076,2025-02-12 12:51:07,Публикатор: Анастасия Патрикеева\nОбсуждение в...,telegram,True
3,devops_jobs_feed,20077,2025-02-12 12:51:35,Публикатор: Даниэлла Котовская🖤\nОбсуждение ва...,telegram,True
4,devops_jobs_feed,20080,2025-02-12 17:08:23,Публикатор: Елизавета Бондарева 🌷\nОбсуждение ...,telegram,True
5,devops_jobs_feed,20084,2025-02-13 09:54:27,Публикатор: Margarita Ivanishcheva\nОбсуждение...,telegram,True
...,...,...,...,...,...,...
17300,python_jobs,230863,2025-08-06 10:30:51,#вакансия #backend #python\nBackend-разработчи...,telegram,False
17334,python_jobs,230806,2025-08-04 09:31:27,#Python #вакансия #Москва #офис #fulltime \...,telegram,False
17390,python_jobs,230408,2025-07-23 14:11:57,#вакансия #python #Django #fulltime #офис\n \n...,telegram,False
17422,python_jobs,231356,2025-08-18 13:06:51,#вакансия #backend #python #django #redis #ma...,telegram,False
17540,python_jobs,231008,2025-08-11 15:34:55,#Вакансия #Разработчик #python #работа #remote...,telegram,False

In [242]:
df_tg.reset_index(drop=True)

,channel,message_id,date,text,source,is_high_salary
0,devops_jobs_feed,20051,2025-02-10 09:09:31,Публикатор: Nelly🍒\nОбсуждение вакансии в чате...,telegram,True
1,devops_jobs_feed,20076,2025-02-12 12:51:07,Публикатор: Анастасия Патрикеева\nОбсуждение в...,telegram,True
2,devops_jobs_feed,20077,2025-02-12 12:51:35,Публикатор: Даниэлла Котовская🖤\nОбсуждение ва...,telegram,True
3,devops_jobs_feed,20080,2025-02-12 17:08:23,Публикатор: Елизавета Бондарева 🌷\nОбсуждение ...,telegram,True
4,devops_jobs_feed,20084,2025-02-13 09:54:27,Публикатор: Margarita Ivanishcheva\nОбсуждение...,telegram,True
...,...,...,...,...,...,...
4418,python_jobs,230863,2025-08-06 10:30:51,#вакансия #backend #python\nBackend-разработчи...,telegram,False
4419,python_jobs,230806,2025-08-04 09:31:27,#Python #вакансия #Москва #офис #fulltime \...,telegram,False
4420,python_jobs,230408,2025-07-23 14:11:57,#вакансия #python #Django #fulltime #офис\n \n...,telegram,False
4421,python_jobs,231356,2025-08-18 13:06:51,#вакансия #backend #python #django #redis #ma...,telegram,False
4422,python_jobs,231008,2025-08-11 15:34:55,#Вакансия #Разработчик #python #работа #remote...,telegram,False

In [243]:
df_tg.iloc[2]['text']

'Публикатор: Даниэлла Котовская🖤\nОбсуждение вакансии в чате @devops_jobs\n#вакансия #fulltime #remote #удаленка #middle \n\nКомпания Centicore  находится в поисках DevOps/ SRE. Наша компания занимается продуктовой разработкой проектов наших Заказчиков под ключ. \n\nВакансия:  DevOps/ SRE (опыт работы SRE обязателен) !!!\nФормат работы: Удаленный (Работа по МСК времени) \nВилка: 400-440к на руки (в зависимости от опыта и пожеланий кандидата)\nКомпетенция ИТ-сотрудника: Сопровождение\nТехнический уровень: Middle+\n\n\nУсловия: \n- Удаленный формат работы в IT аккредитованной компании;\n- Длительный проект;\n- Оплачиваемый отпуск 28 календарных дней в год и оплачиваемые больничные;\n- Предоставление техники (MAC,Windows)\n- ДМС;\n- Компенсация хобби/спортзала/англ.яз.;\n- Индексация/пересмотр ЗП;\n- Компенсация проф.обучения;\n- Возможность участия во внутренних программах компании и активностях, например: в реферальной программе «приведи друга»;\n- Услуги корпоративного психолога.\n\n Ожидания:\n— основы сетевого взаимодействия, DNS\n— основы виртуализации серверов\n— практические навыки администрирования Linux (rpm-based)\n— практические навыки работы с Ansible\n— контейнеризация (практические навыки работы с Docker/Podman)\n— оркестрация приложений (практические навыки работы с Kubernetes)\n— практические навыки работы с балансировщиками нагрузки Nginx, HAproxy\n— практические навыки работы с Prometheus, Grafana, ELK\n— основы Kafka, PosgreSQL, MongoDВ, Redis\n— основы CI/CD\n— приветствуется опыт работы API Management платформами WSO2, Gravitee, Tyk\n\nЗадачи:\nИщем SRE middle специалиста в качестве усиления состава в команду сопровождения.\nПоддерживаем работоспособность и доступность Интеграционных Платформ Банка.\nВ нашем ведении промышленная и тестовые среды, подсистемы логирования и мониторинга, траблшутинг и доставка приложений по средам.\n\n\nДля вопросов и резюме - просьба обращаться в лс @ktvsk_d\n\nБуду рада познакомиться!'

Все ок, но мы поняли, что не убрали ссылки в текстах. А ссылки могут содержать 4+ цифры, что мы проверяем в маске, так что уберем и ссылки.

In [244]:
url_pattern = r'https?://\S+|vk\.com/\S+|t\.me/\S+'
df_tg['text'] = df_tg['text'].str.replace(url_pattern, '', regex=True)

In [245]:
has_vacancy = df_tg['text'].str.contains(vacancy_pattern, case=False, na=False)
has_salary = df_tg['text'].str.contains(salary_pattern, case=False, na=False)
mask = ((~channels.isin(hashtag_channels) & has_salary) | (channels.isin(hashtag_channels) & has_vacancy & has_salary))
df_tg = df_tg[mask]
len(df_tg)

/tmp/ipykernel_7964/3938822375.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_tg = df_tg[mask]

4212

Пишем функцию, которая приведет з/п в нормальный вид

In [246]:
def salary_normalizing(matches):
  salaries = []
  for m in matches:
    m = m.strip()
    if any(k in m.lower() for k in ['к', 'k', 'тыс']):
      num = ''.join(c for c in m if c.isdigit())
      if num:
        salaries.append(int(num) * 1000)
    else:
      num = ''.join(c for c in m if c.isdigit())
      if num:
        salaries.append(int(num))
  salaries = [s for s in salaries if 50000 <= s <= 5000000]
  if not salaries:
    return None, None, None
  salary_from = min(salaries)
  salary_to = max(salaries) if len(salaries) > 1 else None
  salary_mid = (salary_from + salary_to) / 2 if salary_to else salary_from
  return salary_from, salary_to, salary_mid

In [247]:
matches = df_tg['text'].str.findall(r'\d[\d\s]*[\.\s]\d{3}|\d{4,}|[1-9]\d{1,2}\s?[кkКK]|\d+\s?тыс')
matches

1                         [420 k]
2              [280 000, 400 000]
3                    [440к, 28 к]
4              [200 000, 400 000]
5              [300 000, 400 000]
                   ...
17300          [200 000, 250 000]
17334          [150 000, 250 000]
17390    [180 000, 250 000, 3000]
17422          [150 000, 180 000]
17540                      [370К]
Name: text, Length: 4212, dtype: object

In [248]:
results = matches.apply(salary_normalizing)
df_tg['salary_from'] = results.apply(lambda x: x[0])
df_tg['salary_to'] = results.apply(lambda x: x[1])
df_tg['salary_mid'] = results.apply(lambda x: x[2])

/tmp/ipykernel_7964/3619170105.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_tg['salary_from'] = results.apply(lambda x: x[0])
/tmp/ipykernel_7964/3619170105.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_tg['salary_to'] = results.apply(lambda x: x[1])
/tmp/ipykernel_7964/3619170105.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_tg['salary_mid'] = results.apply(lambda x: x[2])

In [249]:
df_tg = df_tg.dropna(subset=['salary_from']).reset_index(drop=True)
df_tg

,channel,message_id,date,text,source,is_high_salary,salary_from,salary_to,salary_mid
0,devops_jobs_feed,20051,2025-02-10 09:09:31,Публикатор: Nelly🍒\nОбсуждение вакансии в чате...,telegram,True,420000.0,NaN,420000.0
1,devops_jobs_feed,20076,2025-02-12 12:51:07,Публикатор: Анастасия Патрикеева\nОбсуждение в...,telegram,True,280000.0,400000.0,340000.0
2,devops_jobs_feed,20077,2025-02-12 12:51:35,Публикатор: Даниэлла Котовская🖤\nОбсуждение ва...,telegram,True,440000.0,NaN,440000.0
3,devops_jobs_feed,20080,2025-02-12 17:08:23,Публикатор: Елизавета Бондарева 🌷\nОбсуждение ...,telegram,True,200000.0,400000.0,300000.0
4,devops_jobs_feed,20084,2025-02-13 09:54:27,Публикатор: Margarita Ivanishcheva\nОбсуждение...,telegram,True,300000.0,400000.0,350000.0
...,...,...,...,...,...,...,...,...,...
3296,python_jobs,230863,2025-08-06 10:30:51,#вакансия #backend #python\nBackend-разработчи...,telegram,False,200000.0,250000.0,225000.0
3297,python_jobs,230806,2025-08-04 09:31:27,#Python #вакансия #Москва #офис #fulltime \...,telegram,False,150000.0,250000.0,200000.0
3298,python_jobs,230408,2025-07-23 14:11:57,#вакансия #python #Django #fulltime #офис\n \n...,telegram,False,180000.0,250000.0,215000.0
3299,python_jobs,231356,2025-08-18 13:06:51,#вакансия #backend #python #django #redis #ma...,telegram,False,150000.0,180000.0,165000.0
3300,python_jobs,231008,2025-08-11 15:34:55,#Вакансия #Разработчик #python #работа #remote...,telegram,False,370000.0,NaN,370000.0

На всякий случай перезаполним наш is_high_salary на условие зп от 400к руб

In [250]:
df_tg['is_high_salary'] = df_tg['salary_from'] >= 400000

print(f'Вакансий c зп от 400к {df_tg['is_high_salary'].sum()}')
print(f'Вакансий с зп до 400к {(~df_tg['is_high_salary']).sum()}')

Вакансий c зп от 400к 356
Вакансий с зп до 400к 2945

In [251]:
def grade(text):
  text = text.lower()
  if any(w in text for w in ['senior', 'сеньор', 'сеньора', 'старший', 'старшего']):
    return 'senior'
  elif any(w in text for w in ['middle', 'мидл', 'миддл', 'мидла', 'миддла']):
    return 'middle'
  elif any(w in text for w in ['junior', 'джун', 'джуна', 'младший', 'младшего']):
    return 'junior'
  elif any(w in text for w in ['lead', 'team lead', 'teamlead', 'тимлид', 'тимлида']):
    return 'lead'
  else:
    return None

In [252]:
df_tg['grade'] = df_tg['text'].apply(grade)
df_tg['grade'].value_counts(dropna=False)

grade
None      1307
senior    1102
middle     682
junior     115
lead        95
Name: count, dtype: int64

In [253]:
df_tg[df_tg['grade'].isna()]

,channel,message_id,date,text,source,is_high_salary,salary_from,salary_to,salary_mid,grade
1,devops_jobs_feed,20076,2025-02-12 12:51:07,Публикатор: Анастасия Патрикеева\nОбсуждение в...,telegram,False,280000.0,400000.0,340000.0,None
3,devops_jobs_feed,20080,2025-02-12 17:08:23,Публикатор: Елизавета Бондарева 🌷\nОбсуждение ...,telegram,False,200000.0,400000.0,300000.0,None
12,devops_jobs_feed,20155,2025-02-24 13:31:58,"Публикатор: Marina (IT Recruiter, Selecty)\nОб...",telegram,True,400000.0,NaN,400000.0,None
25,devops_jobs_feed,20033,2025-02-05 17:09:41,Публикатор: Ксения\nОбсуждение вакансии в чате...,telegram,False,350000.0,420000.0,385000.0,None
32,devops_jobs_feed,19886,2025-01-17 11:46:28,Публикатор: Влад Храмов\nОбсуждение вакансии в...,telegram,False,250000.0,600000.0,425000.0,None
...,...,...,...,...,...,...,...,...,...,...
3293,python_jobs,232211,2025-09-11 12:39:17,#вакансия\n\nКомпания: SibirAI \n\nФормат раб...,telegram,False,60000.0,NaN,60000.0,None
3294,python_jobs,230536,2025-07-28 14:29:33,#вакансия #удаленка #python\n\nФормат: удаленн...,telegram,False,250000.0,310000.0,280000.0,None
3296,python_jobs,230863,2025-08-06 10:30:51,#вакансия #backend #python\nBackend-разработчи...,telegram,False,200000.0,250000.0,225000.0,None
3297,python_jobs,230806,2025-08-04 09:31:27,#Python #вакансия #Москва #офис #fulltime \...,telegram,False,150000.0,250000.0,200000.0,None
3298,python_jobs,230408,2025-07-23 14:11:57,#вакансия #python #Django #fulltime #офис\n \n...,telegram,False,180000.0,250000.0,215000.0,None

In [254]:
def work_format(text):
  text = text.lower()
  if any(w in text for w in ['удалён', 'удален', 'удалёнка', 'удаленка', 'remote']):
    return 'remote'
  elif any(w in text for w in ['гибрид', 'hybrid']):
    return 'hybrid'
  elif any(w in text for w in ['офис', 'очно', 'office']):
    return 'office'
  else:
    return None

In [255]:
df_tg['work_format'] = df_tg['text'].apply(work_format)
df_tg['work_format'].value_counts(dropna=False)

work_format
remote    2516
hybrid     383
office     263
None       139
Name: count, dtype: int64

In [256]:
df_tg = df_tg.dropna(subset=['work_format']).reset_index(drop=True)

Дальше наконец отбираем технологии, навыки, умения и знания, которые могут требоваться в вакансиях. Мы составили список из 158 IT-технологий, языков программирования и прочих инструментов, чтобы проверить наличие каждого в тексте вакансии.   

Вакансии без единой технологии из списка мы будем считать нерелевантными, поэтому они будут удалены на следующем шаге.

In [257]:
tech_keywords = [
    'Python', 'JavaScript', 'TypeScript', 'Java', 'Go', 'Golang',
    'C++', 'C#', 'Rust', 'Kotlin', 'Swift', 'PHP', 'Ruby', 'Scala',
    'R', 'Matlab', 'Perl', 'Bash', 'Shell', 'PowerShell',
    'SQL', 'PostgreSQL', 'MySQL', 'MongoDB', 'Redis', 'Kafka',
    'ClickHouse', 'Cassandra', 'Elasticsearch', 'SQLite', 'Oracle',
    'MS SQL', 'MSSQL', 'MariaDB', 'DynamoDB', 'Redshift', 'BigQuery',
    'Snowflake', 'Greenplum', 'Vertica', 'Neo4j', 'RabbitMQ',
    'Pandas', 'NumPy', 'PyTorch', 'TensorFlow', 'Keras', 'Scikit-learn',
    'Spark', 'Airflow', 'dbt', 'Hadoop', 'Hive', 'Flink',
    'Machine Learning', 'Deep Learning', 'NLP', 'LLM', 'Data Science',
    'Computer Vision', 'MLOps', 'DataOps', 'BI', 'ETL', 'ELT',
    'XGBoost', 'CatBoost', 'LightGBM', 'BERT', 'GPT',
    'Django', 'FastAPI', 'Flask', 'Spring', 'SpringBoot',
    'Node.js', 'Express', 'NestJS', 'Laravel', 'Rails',
    'GraphQL', 'REST', 'gRPC', 'WebSocket', 'Celery',
    'React', 'Vue', 'Angular', 'Next.js', 'Nuxt', 'Svelte',
    'HTML', 'CSS', 'Webpack', 'Vite', 'Redux',
    'Docker', 'Kubernetes', 'Terraform', 'Ansible', 'Jenkins',
    'GitLab', 'GitHub', 'CI/CD', 'Linux', 'Nginx', 'Apache',
    'AWS', 'GCP', 'Azure', 'Yandex Cloud', 'VK Cloud',
    'Prometheus', 'Grafana', 'ELK', 'Kibana', 'Logstash',
    'Vault', 'Consul', 'Istio', 'Helm', 'ArgoCD',
    'Tableau', 'Power BI', 'PowerBI', 'Superset', 'Metabase',
    'Looker', 'QlikView', 'Excel', 'Google Sheets',
    '1С', 'SAP', 'Jira', 'Confluence',
    'Android', 'iOS', 'React Native', 'Flutter', 'Xamarin',
    'Selenium', 'Pytest', 'JUnit', 'Postman', 'JMeter',
    'Cypress', 'Playwright', 'Appium', 'TestRail',
    'Git', 'Linux', 'Agile', 'Scrum', 'Kanban',
    'Microservices', 'API', 'S3', 'gRPC'
    ]

In [258]:
def technologies(text):
  found = []
  text_lower = text.lower()
  for tech in tech_keywords:
    tech_lower = tech.lower()
    if tech_lower in text_lower:
      found.append(tech)
  return ', '.join(found) if found else None

In [259]:
df_tg['technologies'] = df_tg['text'].apply(technologies)
df_tg

,channel,message_id,date,text,source,is_high_salary,salary_from,salary_to,salary_mid,grade,work_format,technologies
0,devops_jobs_feed,20051,2025-02-10 09:09:31,Публикатор: Nelly🍒\nОбсуждение вакансии в чате...,telegram,True,420000.0,NaN,420000.0,senior,remote,"Python, Go, R, Docker, Kubernetes, Terraform, ..."
1,devops_jobs_feed,20076,2025-02-12 12:51:07,Публикатор: Анастасия Патрикеева\nОбсуждение в...,telegram,False,280000.0,400000.0,340000.0,None,remote,"R, SQL, MySQL, MSSQL, Docker, Kubernetes, Ansi..."
2,devops_jobs_feed,20077,2025-02-12 12:51:35,Публикатор: Даниэлла Котовская🖤\nОбсуждение ва...,telegram,True,440000.0,NaN,440000.0,middle,remote,"Go, R, SQL, Redis, Kafka, Vite, Docker, Kubern..."
3,devops_jobs_feed,20080,2025-02-12 17:08:23,Публикатор: Елизавета Бондарева 🌷\nОбсуждение ...,telegram,False,200000.0,400000.0,300000.0,None,hybrid,"Python, R, Bash, SQL, PostgreSQL, Ansible, Jen..."
4,devops_jobs_feed,20084,2025-02-13 09:54:27,Публикатор: Margarita Ivanishcheva\nОбсуждение...,telegram,False,300000.0,400000.0,350000.0,junior,remote,"Python, Java, Go, C++, C#, R, Node.js, Docker,..."
...,...,...,...,...,...,...,...,...,...,...,...,...
3157,python_jobs,230863,2025-08-06 10:30:51,#вакансия #backend #python\nBackend-разработчи...,telegram,False,200000.0,250000.0,225000.0,None,remote,"Python, R, Redis, Node.js, REST, WebSocket, API"
3158,python_jobs,230806,2025-08-04 09:31:27,#Python #вакансия #Москва #офис #fulltime \...,telegram,False,150000.0,250000.0,200000.0,None,office,"Python, R, SQL, PostgreSQL, MySQL, Redis, SQLi..."
3159,python_jobs,230408,2025-07-23 14:11:57,#вакансия #python #Django #fulltime #офис\n \n...,telegram,False,180000.0,250000.0,215000.0,None,office,"Python, Go, R, SQL, MySQL, Redis, Kafka, Rabbi..."
3160,python_jobs,231356,2025-08-18 13:06:51,#вакансия #backend #python #django #redis #ma...,telegram,False,150000.0,180000.0,165000.0,middle,remote,"Python, Go, R, SQL, MySQL, Redis, MariaDB, Rab..."
3161,python_jobs,231008,2025-08-11 15:34:55,#Вакансия #Разработчик #python #работа #remote...,telegram,False,370000.0,NaN,370000.0,senior,remote,"Python, R, SQL, PostgreSQL, Kafka, Airflow, ET..."

In [260]:
df_tg['technologies'].isna().sum()

np.int64(35)

In [261]:
df_tg = df_tg.dropna(subset=['technologies']).reset_index(drop=True)
len(df_tg)

3127

In [262]:
def specialization(text):
  text = text.lower()
  if any(w in text for w in ['data engineer', 'дата инженер', 'etl-разработчик']):
    return 'Data Engineer'
  elif any(w in text for w in ['бизнес-аналитик', 'бизнес аналитик', 'business analyst']):
    return 'Business Analyst'
  elif any(w in text for w in ['продуктовый аналитик', 'product analyst', 'маркетинговый аналитик']):
    return 'Product Analyst'
  elif any(w in text for w in ['data analyst', 'data analytics', 'аналитик данных', 'analyst', 'head of data']):
    return 'Data Analyst'
  elif any(w in text for w in ['data scientist', 'data science', 'датасаентист', 'дата саентист']):
    return 'Data Scientist'
  elif any(w in text for w in ['ml engineer', 'machine learning engineer', 'mle', 'mlops', 'ml-инженер', 'ml инженер',
                               'ml разработчик', 'мл инженер', 'мл-инженер', 'мл разработчик']):
    return 'ML Engineer'
  elif any(w in text for w in ['nlp', 'llm', 'computer vision', 'cv engineer', 'нлп', 'ллм', 'компьютерное зрение']):
    return 'AI/NLP Engineer'
  elif any(w in text for w in ['системный аналитик', 'system analyst']):
    return 'System Analyst'
  elif any(w in text for w in ['devops', 'девелопер', 'девопс', 'sre', 'site reliability', 'platform engineer']):
    return 'DevOps/SRE'
  elif any(w in text for w in ['fullstack', 'full stack', 'фулстек', 'full-stack']):
    return 'Fullstack Developer'
  elif any(w in text for w in ['frontend', 'фронтенд', 'front-end', 'front end', 'фронт']):
    return 'Frontend Developer'
  elif any(w in text for w in ['backend', 'бэкенд', 'бекенд', 'back-end', 'back end', 'python разработчик',
                               'python developer', 'java developer', 'java разработчик', 'go разработчик',
                               'go developer', 'php разработчик', 'fastapi developer', 'python/fastapi',
                               'senior python', 'django', 'python/django', 'go разработчик', 'golang разработчик', 'crypto']):
    return 'Backend Developer'
  elif any(w in text for w in ['mobile', 'android', 'ios разработчик', 'ios developer', 'flutter', 'мобильный разработчик']):
    return 'Mobile Developer'
  elif any(w in text for w in ['unity', 'unreal', 'game developer', 'gamedev', 'геймдев', 'юнити']):
    return 'Game Developer'
  elif any(w in text for w in ['qa', 'тестировщик', 'test engineer', 'quality assurance', 'автоматизатор']):
    return 'QA Engineer'
  elif any(w in text for w in ['security', 'информационная безопасность', 'кибербезопасность',
                               'инфбез', 'пентест', 'pentest']):
    return 'Security Engineer'
  elif any(w in text for w in ['архитектор', 'architect', 'solution architect']):
    return 'Architect'
  elif any(w in text for w in ['team lead', 'teamlead', 'тимлид', 'tech lead', 'техлид', 'engineering manager', 'руководитель разработки']):
    return 'Tech Lead/Manager'
  elif any(w in text for w in ['1с программист', '1с разработчик', '1с аналитик']):
    return '1C Developer'
  elif any(w in text for w in ['scrum master', 'agile coach', 'project manager', 'проджект менеджер', 'менеджер проекта']):
    return 'Project/Scrum Manager'
  elif any(w in text for w in ['ux', 'ui', 'дизайнер', 'product designer']):
    return 'UX/UI Designer'
  else:
    return None

In [263]:
df_tg['specialization'] = df_tg['text'].apply(specialization)
df_tg

,channel,message_id,date,text,source,is_high_salary,salary_from,salary_to,salary_mid,grade,work_format,technologies,specialization
0,devops_jobs_feed,20051,2025-02-10 09:09:31,Публикатор: Nelly🍒\nОбсуждение вакансии в чате...,telegram,True,420000.0,NaN,420000.0,senior,remote,"Python, Go, R, Docker, Kubernetes, Terraform, ...",DevOps/SRE
1,devops_jobs_feed,20076,2025-02-12 12:51:07,Публикатор: Анастасия Патрикеева\nОбсуждение в...,telegram,False,280000.0,400000.0,340000.0,None,remote,"R, SQL, MySQL, MSSQL, Docker, Kubernetes, Ansi...",DevOps/SRE
2,devops_jobs_feed,20077,2025-02-12 12:51:35,Публикатор: Даниэлла Котовская🖤\nОбсуждение ва...,telegram,True,440000.0,NaN,440000.0,middle,remote,"Go, R, SQL, Redis, Kafka, Vite, Docker, Kubern...",DevOps/SRE
3,devops_jobs_feed,20080,2025-02-12 17:08:23,Публикатор: Елизавета Бондарева 🌷\nОбсуждение ...,telegram,False,200000.0,400000.0,300000.0,None,hybrid,"Python, R, Bash, SQL, PostgreSQL, Ansible, Jen...",DevOps/SRE
4,devops_jobs_feed,20084,2025-02-13 09:54:27,Публикатор: Margarita Ivanishcheva\nОбсуждение...,telegram,False,300000.0,400000.0,350000.0,junior,remote,"Python, Java, Go, C++, C#, R, Node.js, Docker,...",DevOps/SRE
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3122,python_jobs,230863,2025-08-06 10:30:51,#вакансия #backend #python\nBackend-разработчи...,telegram,False,200000.0,250000.0,225000.0,None,remote,"Python, R, Redis, Node.js, REST, WebSocket, API",Frontend Developer
3123,python_jobs,230806,2025-08-04 09:31:27,#Python #вакансия #Москва #офис #fulltime \...,telegram,False,150000.0,250000.0,200000.0,None,office,"Python, R, SQL, PostgreSQL, MySQL, Redis, SQLi...",UX/UI Designer
3124,python_jobs,230408,2025-07-23 14:11:57,#вакансия #python #Django #fulltime #офис\n \n...,telegram,False,180000.0,250000.0,215000.0,None,office,"Python, Go, R, SQL, MySQL, Redis, Kafka, Rabbi...",DevOps/SRE
3125,python_jobs,231356,2025-08-18 13:06:51,#вакансия #backend #python #django #redis #ma...,telegram,False,150000.0,180000.0,165000.0,middle,remote,"Python, Go, R, SQL, MySQL, Redis, MariaDB, Rab...",Backend Developer
3126,python_jobs,231008,2025-08-11 15:34:55,#Вакансия #Разработчик #python #работа #remote...,telegram,False,370000.0,NaN,370000.0,senior,remote,"Python, R, SQL, PostgreSQL, Kafka, Airflow, ET...",None

In [264]:
df_tg['specialization'].value_counts(dropna=False)

specialization
DevOps/SRE             1786
None                    235
Data Analyst            159
ML Engineer             153
Backend Developer       148
Data Scientist          117
Data Engineer           113
AI/NLP Engineer          83
Business Analyst         74
System Analyst           65
Product Analyst          55
UX/UI Designer           41
Frontend Developer       35
Fullstack Developer      19
Architect                14
Mobile Developer         11
QA Engineer              10
Tech Lead/Manager         5
Game Developer            4
Name: count, dtype: int64

In [265]:
print(245 / 3915 * 100)

6.257982120051085

Доля NaN всего 6.3%, спокойно дропаем их.

In [266]:
df_tg = df_tg.dropna(subset=['specialization']).reset_index(drop=True)
len(df_tg)

2892

In [268]:
df_tg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2892 entries, 0 to 2891
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   channel         2892 non-null   object
 1   message_id      2892 non-null   int64
 2   date            2892 non-null   object
 3   text            2892 non-null   object
 4   source          2892 non-null   object
 5   is_high_salary  2892 non-null   bool
 6   salary_from     2892 non-null   float64
 7   salary_to       1917 non-null   float64
 8   salary_mid      2892 non-null   float64
 9   grade           1879 non-null   object
 10  work_format     2892 non-null   object
 11  technologies    2892 non-null   object
 12  specialization  2892 non-null   object
dtypes: bool(1), float64(3), int64(1), object(8)
memory usage: 274.1+ KB

In [270]:
df_tg.to_csv('df_tg.csv')