In [1]:
import numpy as np
import pandas as pd
import re

In [63]:
df1 = pd.read_csv('hh.csv')
df1 = df1.drop(columns='Unnamed: 0')
df1.head(5)

,url,title,date,company,salary,experience,location,tags_raw,description,source
0,https://hh.ru/vacancy/131901278,Аналитик данных,2026-04-10 20:18:24,ОООИнсейлс Рус,NaN,1–3 года,NaN,"Анализ данных, SQL, PostgreSQL, Clickhouse",inSales — это многоканальная платформа управле...,hh_ru
1,https://hh.ru/vacancy/132016213,Финансовый аналитик,2026-04-10 20:16:52,РБК,до 130 000 ₽ за месяц на руки,1–3 года,NaN,"SQL, Power Query, Power Pivot, Power BI",Чем предстоит заниматься: Ежедневный бюджетный...,hh_ru
2,https://hh.ru/vacancy/132017454,Аналитик данных,2026-04-10 19:09:59,ПАОМосковская Биржа,NaN,1–3 года,NaN,NaN,В 2022 году Московской бирже исполнилось 30 ле...,hh_ru
3,https://hh.ru/vacancy/131878189,Аналитик CX,2026-04-10 18:31:17,Группа компаний МЕДСИ,от 260 000 ₽ за месяц до вычета налогов,3–6 лет,NaN,NaN,"Обязанности: Сбор, структурирование и оцифровк...",hh_ru
4,https://hh.ru/vacancy/131274058,Аналитик данных,2026-04-10 17:34:21,Росфинмониторинг,от 80 000 до 110 000 ₽ за месяц на руки,1–3 года,NaN,"MS Excel, Работа с большим объемом информации,...","Обязанности: сбор, обработка и анализ данных, ...",hh_ru

In [64]:
df2 = pd.read_csv('hh2.csv')
df2 = df2.drop(columns='Unnamed: 0')
df2.head(5)

,url,title,date,company,salary,experience,location,tags_raw,description,source
0,https://hh.ru/vacancy/131672943,Product Manager | Менеджер продукта,2026-04-10 20:54:01,Альфа-Деньги,NaN,не требуется,NaN,"Управление продуктом, Atlassian Jira, Atlassia...",Привет! Альфа-Деньги — это команда единомышлен...,hh_ru
1,https://hh.ru/vacancy/131577825,Менеджер продукта (Junior Product Manager),2026-04-10 19:19:24,ОООРусдронопорт,до 120 000 ₽ за месяц на руки,1–3 года,NaN,"Аналитическое мышление, Визуализация данных, У...","Компания ""РУСДРОНОПОРТ"" — аккредитованная IT-к...",hh_ru
2,https://hh.ru/vacancy/131955694,Директор по информационным технологиям (CIO),2026-04-10 18:23:57,"Оптиком, компания",NaN,более 6 лет,NaN,NaN,"Роль для лидера, который умеет превращать IT в...",hh_ru
3,https://hh.ru/vacancy/131876872,Machine Learning Engineer,2026-04-10 18:23:05,TrafficStars,NaN,3–6 лет,NaN,"Python, Clickhouse, A/B тесты, Data Analysis, ...",Мы -международная продуктовая AdTech-компания ...,hh_ru
4,https://hh.ru/vacancy/131907994,Data Engineer,2026-04-10 17:12:00,Karuna,NaN,1–3 года,NaN,"Python, SQL, ETL, Kubernetes, Apache Airflow","Каруна — это сообщество, где твои идеи становя...",hh_ru

In [65]:
df3 = pd.read_csv('hh3.csv')
df3 = df3.drop(columns='Unnamed: 0')
df3.head(5)

,url,title,date,company,salary,experience,location,tags_raw,description,source
0,https://hh.ru/vacancy/121431371,Категорийный менеджер,2026-04-10 19:10:10,ГК Лит Трейдинг,"от 200 000 ₽ за месяц, до вычета налогов",1–3 года,NaN,NaN,"Мы ищем специалиста, который обеспечит рыночны...",hh_ru
1,https://hh.ru/vacancy/102357219,3D Character Artist/стажёр (Художник по персон...,2026-04-10 18:13:05,Парамонов Дмитрий,NaN,не требуется,NaN,"ZBrush, Blender 3D, 3D Max, 3D Моделирование",Мы ищем увлеченных 3D графикой людей на позици...,hh_ru
2,https://hh.ru/vacancy/120432786,2D-художник,2026-04-10 15:41:50,FunFlow (ООО Мобильные Игровые Решения),"от 80 000 до 150 000 ₽ за месяц, на руки",1–3 года,NaN,"Adobe Photoshop, Stable Diffusion, Midjourney","FunFlow – аккредитованная IT-компания, разрабо...",hh_ru
3,https://hh.ru/vacancy/124216682,Дизайнер интерьеров/технический дизайнер/черте...,2026-04-10 15:09:01,АН Магазин Квартир,"от 100 000 ₽ за месяц , на руки",1–3 года,NaN,"Дизайн интерьера, ArchiCAD, 3ds Max, Визуализа...","""White Flat"" — один из лидеров рынка в направл...",hh_ru
4,https://hh.ru/vacancy/122720491,Графический дизайнер,2026-04-10 13:42:24,ОООЛенремонт,"от 90 000 до 100 000 ₽ за месяц , на руки",1–3 года,NaN,"Adobe Photoshop, Figma, Навыки работы с нейрос...",Компания ЛЕНРЕМОНТ – лидер рынка ремонтных усл...,hh_ru

In [66]:
df4 = pd.read_csv('hh4.csv')
df4 = df4.drop(columns='Unnamed: 0')
df4.head(5)

,url,title,date,company,salary,experience,location,tags_raw,description,source
0,https://hh.ru/vacancy/131814097,Системный аналитик,2026-04-10 20:40:03,ОООБрайтис,NaN,3–6 лет,NaN,"SQL, Микросервисная архитектура, Системный ана...","📄Российская ИТ компания, по модели B2B2C предо...",hh_ru
1,https://hh.ru/vacancy/131991064,Ведущий системный аналитик,2026-04-10 20:35:03,Freedom International Group,от 300 000 до 400 000 ₽ за месяц на руки,более 6 лет,NaN,Английский — C1 — Продвинутый,Freedom Group International - инвестиционный х...,hh_ru
2,https://hh.ru/vacancy/132011527,Руководитель отдела IT,2026-04-10 20:12:10,АООКАН,NaN,3–6 лет,NaN,"Руководство коллективом, SQL, Администрирование",Привет! Мы — инженерная компания «ОКАН». Обесп...,hh_ru
3,https://hh.ru/vacancy/131827660,Менеджер отдела специальных проектов,2026-04-10 20:09:59,Иви,NaN,более 6 лет,NaN,NaN,Иви — один из лидеров рынка онлайн-кинотеатров...,hh_ru
4,https://hh.ru/vacancy/131959221,Начальник отдела информационных технологий,2026-04-10 19:20:23,АОНИИТФА,NaN,3–6 лет,NaN,NaN,АО «НИИТФА» - Научно-исследовательский институ...,hh_ru

In [67]:
df5 = pd.read_csv('hh5.csv')
df5 = df5.drop(columns='Unnamed: 0')
df5.head(5)

,url,title,date,company,salary,experience,location,tags_raw,description,source
0,https://hh.ru/vacancy/132009820,Специалист по ручному тестированию,2026-04-10 20:42:48,ПАОБАНК УРАЛСИБ,NaN,3–6 лет,NaN,"SQL, XML, JSON, Apache Kafka",Чем предстоит заниматься: • написанием тест-ке...,hh_ru
1,https://hh.ru/vacancy/131815782,Инженер по тестированию/QA-инженер,2026-04-10 18:18:41,Standfin,NaN,1–3 года,NaN,NaN,"Standfin - компания, которая с 2022 года помог...",hh_ru
2,https://hh.ru/vacancy/131946220,Специалист по ручному тестированию,2026-04-10 18:16:12,АОСинтелс,NaN,3–6 лет,NaN,"Ручное тестирование, Тестирование десктопных п...",Обязанности: Ручное тестирование программного ...,hh_ru
3,https://hh.ru/vacancy/132024232,Тестировщик ПО ручное тестирование (Санкт-Пете...,2026-04-10 15:49:24,Смарт Телеком,от 70 000 ₽ за месяц на руки,1–3 года,NaN,"Ручное тестирование, Тестирование ПО, Анализ т...",Смарт Телеком — компания один из крупнейших ун...,hh_ru
4,https://hh.ru/vacancy/131978677,Специалист технической поддержки,2026-04-10 14:59:48,Группа Компаний «Аскона» | IT,от 100 000 до 120 000 ₽ за месяц до вычета нал...,1–3 года,NaN,"1С, SQL, Kibana, Grafana, Техническая поддержка",Аскона — крупная федеральная компания с более ...,hh_ru

In [68]:
df_hh = pd.concat([df1, df2, df3, df4, df5], ignore_index=True)
df_hh

,url,title,date,company,salary,experience,location,tags_raw,description,source
0,https://hh.ru/vacancy/131901278,Аналитик данных,2026-04-10 20:18:24,ОООИнсейлс Рус,NaN,1–3 года,NaN,"Анализ данных, SQL, PostgreSQL, Clickhouse",inSales — это многоканальная платформа управле...,hh_ru
1,https://hh.ru/vacancy/132016213,Финансовый аналитик,2026-04-10 20:16:52,РБК,до 130 000 ₽ за месяц на руки,1–3 года,NaN,"SQL, Power Query, Power Pivot, Power BI",Чем предстоит заниматься: Ежедневный бюджетный...,hh_ru
2,https://hh.ru/vacancy/132017454,Аналитик данных,2026-04-10 19:09:59,ПАОМосковская Биржа,NaN,1–3 года,NaN,NaN,В 2022 году Московской бирже исполнилось 30 ле...,hh_ru
3,https://hh.ru/vacancy/131878189,Аналитик CX,2026-04-10 18:31:17,Группа компаний МЕДСИ,от 260 000 ₽ за месяц до вычета налогов,3–6 лет,NaN,NaN,"Обязанности: Сбор, структурирование и оцифровк...",hh_ru
4,https://hh.ru/vacancy/131274058,Аналитик данных,2026-04-10 17:34:21,Росфинмониторинг,от 80 000 до 110 000 ₽ за месяц на руки,1–3 года,NaN,"MS Excel, Работа с большим объемом информации,...","Обязанности: сбор, обработка и анализ данных, ...",hh_ru
...,...,...,...,...,...,...,...,...,...,...
9995,https://hh.ru/vacancy/129632407,Оператор поддержки на арабском языке в г. Волг...,2025-07-16 09:56:22,КонтакПро,от 57 000 ₽ за месяц на руки,не требуется,NaN,"Деловая коммуникация, Деловая переписка, Телеф...",Мы динамично развивающийся отдел поддержки в I...,hh_ru
9996,https://hh.ru/vacancy/131656283,Специалист технической поддержки,2025-07-16 08:51:09,АОИнтернет Проекты,до 120 000 ₽ за месяц на руки,1–3 года,NaN,NaN,"Компания ""Интернет Проекты"" существует более 2...",hh_ru
9997,https://hh.ru/vacancy/131866398,Инженер по информационной безопасности,2025-07-16 07:37:04,ЭОС,NaN,3–6 лет,NaN,NaN,Обязанности: Внедрение технических средств защ...,hh_ru
9998,https://hh.ru/vacancy/131255944,Специалист технической поддержки,2025-07-15 19:45:35,ТЕЛ,NaN,не требуется,NaN,NaN,Компания TEL - 27 лет на рынке телекоммуникаци...,hh_ru
9999,https://hh.ru/vacancy/132021566,Специалист по защите информации,2025-07-15 19:33:35,АВТОВАЗ,NaN,1–3 года,NaN,NaN,Обязанности: Предоставление консультации архит...,hh_ru

In [69]:
df_hh.duplicated().sum()

np.int64(93)

In [70]:
df_hh = df_hh.drop_duplicates()
df_hh = df_hh.reset_index(drop=True)
df_hh

,url,title,date,company,salary,experience,location,tags_raw,description,source
0,https://hh.ru/vacancy/131901278,Аналитик данных,2026-04-10 20:18:24,ОООИнсейлс Рус,NaN,1–3 года,NaN,"Анализ данных, SQL, PostgreSQL, Clickhouse",inSales — это многоканальная платформа управле...,hh_ru
1,https://hh.ru/vacancy/132016213,Финансовый аналитик,2026-04-10 20:16:52,РБК,до 130 000 ₽ за месяц на руки,1–3 года,NaN,"SQL, Power Query, Power Pivot, Power BI",Чем предстоит заниматься: Ежедневный бюджетный...,hh_ru
2,https://hh.ru/vacancy/132017454,Аналитик данных,2026-04-10 19:09:59,ПАОМосковская Биржа,NaN,1–3 года,NaN,NaN,В 2022 году Московской бирже исполнилось 30 ле...,hh_ru
3,https://hh.ru/vacancy/131878189,Аналитик CX,2026-04-10 18:31:17,Группа компаний МЕДСИ,от 260 000 ₽ за месяц до вычета налогов,3–6 лет,NaN,NaN,"Обязанности: Сбор, структурирование и оцифровк...",hh_ru
4,https://hh.ru/vacancy/131274058,Аналитик данных,2026-04-10 17:34:21,Росфинмониторинг,от 80 000 до 110 000 ₽ за месяц на руки,1–3 года,NaN,"MS Excel, Работа с большим объемом информации,...","Обязанности: сбор, обработка и анализ данных, ...",hh_ru
...,...,...,...,...,...,...,...,...,...,...
9902,https://hh.ru/vacancy/129632407,Оператор поддержки на арабском языке в г. Волг...,2025-07-16 09:56:22,КонтакПро,от 57 000 ₽ за месяц на руки,не требуется,NaN,"Деловая коммуникация, Деловая переписка, Телеф...",Мы динамично развивающийся отдел поддержки в I...,hh_ru
9903,https://hh.ru/vacancy/131656283,Специалист технической поддержки,2025-07-16 08:51:09,АОИнтернет Проекты,до 120 000 ₽ за месяц на руки,1–3 года,NaN,NaN,"Компания ""Интернет Проекты"" существует более 2...",hh_ru
9904,https://hh.ru/vacancy/131866398,Инженер по информационной безопасности,2025-07-16 07:37:04,ЭОС,NaN,3–6 лет,NaN,NaN,Обязанности: Внедрение технических средств защ...,hh_ru
9905,https://hh.ru/vacancy/131255944,Специалист технической поддержки,2025-07-15 19:45:35,ТЕЛ,NaN,не требуется,NaN,NaN,Компания TEL - 27 лет на рынке телекоммуникаци...,hh_ru
9906,https://hh.ru/vacancy/132021566,Специалист по защите информации,2025-07-15 19:33:35,АВТОВАЗ,NaN,1–3 года,NaN,NaN,Обязанности: Предоставление консультации архит...,hh_ru

In [71]:
df_hh = df_hh[df_hh['salary'].notna()]
df_hh

,url,title,date,company,salary,experience,location,tags_raw,description,source
1,https://hh.ru/vacancy/132016213,Финансовый аналитик,2026-04-10 20:16:52,РБК,до 130 000 ₽ за месяц на руки,1–3 года,NaN,"SQL, Power Query, Power Pivot, Power BI",Чем предстоит заниматься: Ежедневный бюджетный...,hh_ru
3,https://hh.ru/vacancy/131878189,Аналитик CX,2026-04-10 18:31:17,Группа компаний МЕДСИ,от 260 000 ₽ за месяц до вычета налогов,3–6 лет,NaN,NaN,"Обязанности: Сбор, структурирование и оцифровк...",hh_ru
4,https://hh.ru/vacancy/131274058,Аналитик данных,2026-04-10 17:34:21,Росфинмониторинг,от 80 000 до 110 000 ₽ за месяц на руки,1–3 года,NaN,"MS Excel, Работа с большим объемом информации,...","Обязанности: сбор, обработка и анализ данных, ...",hh_ru
8,https://hh.ru/vacancy/131830629,Стажер-аналитик,2026-04-10 09:01:05,Changellenge,65 000 ₽ за месяц до вычета налогов,не требуется,NaN,NaN,ИТ-кластер «Газпром нефти» — драйвер цифровой ...,hh_ru
9,https://hh.ru/vacancy/131873460,Бизнес-аналитик,2026-04-10 07:29:16,АОНПФ Газфонд пенсионные накопления,от 250 000 ₽ за месяц до вычета налогов,3–6 лет,NaN,"Анализ бизнес-процессов, Моделирование бизнес-...",АО НПФ «ГАЗФОНД пенсионные накопления» — это н...,hh_ru
...,...,...,...,...,...,...,...,...,...,...
9896,https://hh.ru/vacancy/131936734,Специалист отдела поддержки продаж,2025-07-17 15:14:07,БорисХоф,до 120 000 ₽ за месяц до вычета налогов,1–3 года,NaN,"Делопроизводство, Работа с большим объемом инф...",Группа компаний «БорисХоф» – это 30 лет безупр...,hh_ru
9897,https://hh.ru/vacancy/131762219,Специалист технической поддержки,2025-07-17 10:50:50,ОООКомпания Диалог,от 100 000 ₽ за месяц на руки,3–6 лет,NaN,"Работа в команде, Офисная техника, Локальные с...",В ИТ-компанию «Диалог» (1С-Франчайзи) требуетс...,hh_ru
9899,https://hh.ru/vacancy/131378118,Специалист по документообороту (Оператор 1С),2025-07-16 20:23:36,ОООПремиум,55 000 ₽ за месяц на руки,1–3 года,NaN,NaN,Обязанности: - работа в ФГИС Меркурий - работа...,hh_ru
9902,https://hh.ru/vacancy/129632407,Оператор поддержки на арабском языке в г. Волг...,2025-07-16 09:56:22,КонтакПро,от 57 000 ₽ за месяц на руки,не требуется,NaN,"Деловая коммуникация, Деловая переписка, Телеф...",Мы динамично развивающийся отдел поддержки в I...,hh_ru
9903,https://hh.ru/vacancy/131656283,Специалист технической поддержки,2025-07-16 08:51:09,АОИнтернет Проекты,до 120 000 ₽ за месяц на руки,1–3 года,NaN,NaN,"Компания ""Интернет Проекты"" существует более 2...",hh_ru

In [72]:
def split_salary(s):
  s = str(s).replace('\xa0', ' ')
  nums = re.findall(r'\d[\d ]*', s)
  numbers = []
  for part in nums:
    part = part.replace(' ', '')
    numbers.append(float(part))
  if len(numbers) == 0:
    return np.nan, np.nan, np.nan
  if len(numbers) == 1:
    salary_from = numbers[0]
    salary_to = np.nan
    salary_mid = numbers[0]
    return salary_from, salary_to, salary_mid
  salary_from = min(numbers[0], numbers[1])
  salary_to = max(numbers[0], numbers[1])
  salary_mid = (salary_from + salary_to)/2

  return float(salary_from), float(salary_to), float(salary_mid)

In [73]:
sal_from = []
sal_to = []
sal_mid = []

for s in df_hh['salary']:
  salary_from, salary_to, salary_mid = split_salary(s)
  sal_from.append(salary_from)
  sal_to.append(salary_to)
  sal_mid.append(salary_mid)

df_hh['salary_from'] = sal_from
df_hh['salary_to'] = sal_to
df_hh['salary_mid'] = sal_mid
df_hh

/tmp/ipykernel_3720/2098790748.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_hh['salary_from'] = sal_from
/tmp/ipykernel_3720/2098790748.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_hh['salary_to'] = sal_to
/tmp/ipykernel_3720/2098790748.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_hh['salary_mid'] = sal_mid

,url,title,date,company,salary,experience,location,tags_raw,description,source,salary_from,salary_to,salary_mid
1,https://hh.ru/vacancy/132016213,Финансовый аналитик,2026-04-10 20:16:52,РБК,до 130 000 ₽ за месяц на руки,1–3 года,NaN,"SQL, Power Query, Power Pivot, Power BI",Чем предстоит заниматься: Ежедневный бюджетный...,hh_ru,130000.0,NaN,130000.0
3,https://hh.ru/vacancy/131878189,Аналитик CX,2026-04-10 18:31:17,Группа компаний МЕДСИ,от 260 000 ₽ за месяц до вычета налогов,3–6 лет,NaN,NaN,"Обязанности: Сбор, структурирование и оцифровк...",hh_ru,260000.0,NaN,260000.0
4,https://hh.ru/vacancy/131274058,Аналитик данных,2026-04-10 17:34:21,Росфинмониторинг,от 80 000 до 110 000 ₽ за месяц на руки,1–3 года,NaN,"MS Excel, Работа с большим объемом информации,...","Обязанности: сбор, обработка и анализ данных, ...",hh_ru,80000.0,110000.0,95000.0
8,https://hh.ru/vacancy/131830629,Стажер-аналитик,2026-04-10 09:01:05,Changellenge,65 000 ₽ за месяц до вычета налогов,не требуется,NaN,NaN,ИТ-кластер «Газпром нефти» — драйвер цифровой ...,hh_ru,65000.0,NaN,65000.0
9,https://hh.ru/vacancy/131873460,Бизнес-аналитик,2026-04-10 07:29:16,АОНПФ Газфонд пенсионные накопления,от 250 000 ₽ за месяц до вычета налогов,3–6 лет,NaN,"Анализ бизнес-процессов, Моделирование бизнес-...",АО НПФ «ГАЗФОНД пенсионные накопления» — это н...,hh_ru,250000.0,NaN,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9896,https://hh.ru/vacancy/131936734,Специалист отдела поддержки продаж,2025-07-17 15:14:07,БорисХоф,до 120 000 ₽ за месяц до вычета налогов,1–3 года,NaN,"Делопроизводство, Работа с большим объемом инф...",Группа компаний «БорисХоф» – это 30 лет безупр...,hh_ru,120000.0,NaN,120000.0
9897,https://hh.ru/vacancy/131762219,Специалист технической поддержки,2025-07-17 10:50:50,ОООКомпания Диалог,от 100 000 ₽ за месяц на руки,3–6 лет,NaN,"Работа в команде, Офисная техника, Локальные с...",В ИТ-компанию «Диалог» (1С-Франчайзи) требуетс...,hh_ru,100000.0,NaN,100000.0
9899,https://hh.ru/vacancy/131378118,Специалист по документообороту (Оператор 1С),2025-07-16 20:23:36,ОООПремиум,55 000 ₽ за месяц на руки,1–3 года,NaN,NaN,Обязанности: - работа в ФГИС Меркурий - работа...,hh_ru,55000.0,NaN,55000.0
9902,https://hh.ru/vacancy/129632407,Оператор поддержки на арабском языке в г. Волг...,2025-07-16 09:56:22,КонтакПро,от 57 000 ₽ за месяц на руки,не требуется,NaN,"Деловая коммуникация, Деловая переписка, Телеф...",Мы динамично развивающийся отдел поддержки в I...,hh_ru,57000.0,NaN,57000.0
9903,https://hh.ru/vacancy/131656283,Специалист технической поддержки,2025-07-16 08:51:09,АОИнтернет Проекты,до 120 000 ₽ за месяц на руки,1–3 года,NaN,NaN,"Компания ""Интернет Проекты"" существует более 2...",hh_ru,120000.0,NaN,120000.0

In [74]:
df_hh.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4896 entries, 1 to 9903
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   url          4896 non-null   object
 1   title        4896 non-null   object
 2   date         4896 non-null   object
 3   company      4890 non-null   object
 4   salary       4896 non-null   object
 5   experience   4896 non-null   object
 6   location     0 non-null      float64
 7   tags_raw     3367 non-null   object
 8   description  4883 non-null   object
 9   source       4896 non-null   object
 10  salary_from  4896 non-null   float64
 11  salary_to    1972 non-null   float64
 12  salary_mid   4896 non-null   float64
dtypes: float64(4), object(9)
memory usage: 664.5+ KB

In [75]:
df_hh = df_hh[df_hh['salary'].str.contains('₽', na=False)].reset_index(drop=True)
len(df_hh)

4790

In [76]:
df_hh = df_hh[df_hh['salary_from'] >= 50000].reset_index(drop=True)
df_hh = df_hh[df_hh['salary_from'] <= 5000000].reset_index(drop=True)
len(df_hh)

4312

In [77]:
df_hh['is_high_salary'] = df_hh['salary_from'] >= 400000
df_hh = df_hh.sort_values('is_high_salary', ascending=False)

In [78]:
df_hh['text'] = df_hh['title'].fillna('') + ' ' + df_hh['description'].fillna('')
df_hh

,url,title,date,company,salary,experience,location,tags_raw,description,source,salary_from,salary_to,salary_mid,is_high_salary,text
3888,https://hh.ru/vacancy/131586658,Заместитель генерального директора по строител...,2025-11-11 20:13:24,ОООГрант+,до 800 000 ₽ за месяц на руки,3–6 лет,NaN,"Производственное планирование, Оптимизация биз...","Обязанности: Организация, контроль и обеспечен...",hh_ru,800000.0,NaN,800000.0,True,Заместитель генерального директора по строител...
854,https://hh.ru/vacancy/131510357,Руководитель направления электронной коммерции,2026-02-19 10:15:52,ОООЭто Платежи,до 500 000 ₽ за месяц на руки,более 6 лет,NaN,"Управление командой, E-Commerce, Системный под...",О вакансии В связи с расширением деятельности ...,hh_ru,500000.0,NaN,500000.0,True,Руководитель направления электронной коммерции...
2899,https://hh.ru/vacancy/130601098,Руководитель проектов (реинжиниринг),2025-11-10 15:40:29,Diamond Personnel R&C,до 450 000 ₽ за месяц на руки,3–6 лет,NaN,Реинжиниринг бизнес-процессов,Обязанности: Управление проектами по реинжинир...,hh_ru,450000.0,NaN,450000.0,True,Руководитель проектов (реинжиниринг) Обязаннос...
899,https://hh.ru/vacancy/131576330,Lead AI R&D Engineer,2026-02-02 13:47:19,ОООМК Групп,от 500 000 ₽ за месяц на руки,3–6 лет,NaN,"Python, Разработка нового продукта",В Инссмарт мы строим не очередную “AI-инициати...,hh_ru,500000.0,NaN,500000.0,True,Lead AI R&D Engineer В Инссмарт мы строим не о...
1011,https://hh.ru/vacancy/131297065,UX/CX Product Owner (Customer Journey Expert),2025-12-22 13:11:30,ОООМФК ВЭББАНКИР,до 400 000 ₽ за месяц на руки,3–6 лет,NaN,"UX, Customer Journey Mapping, Agile Project Ma...",Ищем опытного специалиста для развития и оптим...,hh_ru,400000.0,NaN,400000.0,True,UX/CX Product Owner (Customer Journey Expert) ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1463,https://hh.ru/vacancy/131295754,Дизайнер сайтов на Tilda,2026-03-10 09:45:40,MAXVAL Marketing&Consulting,"от 55 000 до 70 000 ₽ за месяц , на руки",1–3 года,NaN,"Figma, Web-дизайн, UX, UI/UX, Adobe Photoshop,...",Обязанности: Корректировки сайтов на конструкт...,hh_ru,55000.0,70000.0,62500.0,False,Дизайнер сайтов на Tilda Обязанности: Корректи...
1464,https://hh.ru/vacancy/131297842,Дизайнер,2026-03-10 09:21:55,Prime Недвижимость,"от 80 000 до 100 000 ₽ за месяц , на руки",1–3 года,NaN,NaN,"Привет, меня зовут Аня, я руководитель отдела ...",hh_ru,80000.0,100000.0,90000.0,False,"Дизайнер Привет, меня зовут Аня, я руководител..."
1465,https://hh.ru/vacancy/131298203,UX/UI-дизайнер,2026-03-10 08:30:23,Advline,"от 100 000 ₽ за месяц , до вычета налогов",3–6 лет,NaN,NaN,"Рекламное агентство ""Advline"" в поисках UX/UI-...",hh_ru,100000.0,NaN,100000.0,False,"UX/UI-дизайнер Рекламное агентство ""Advline"" в..."
1466,https://hh.ru/vacancy/131299757,Дизайнер интерьеров,2026-03-10 08:14:01,ОООЗагородная Инвестиционная Компания,"от 150 000 ₽ за месяц , на руки",более 6 лет,NaN,"Дизайн интерьера, 3ds Max, Adobe Photoshop, 3D...",Обязанности: Разработка концепции и стиля инте...,hh_ru,150000.0,NaN,150000.0,False,Дизайнер интерьеров Обязанности: Разработка ко...
4311,https://hh.ru/vacancy/131656283,Специалист технической поддержки,2025-07-16 08:51:09,АОИнтернет Проекты,до 120 000 ₽ за месяц на руки,1–3 года,NaN,NaN,"Компания ""Интернет Проекты"" существует более 2...",hh_ru,120000.0,NaN,120000.0,False,"Специалист технической поддержки Компания ""Инт..."

In [79]:
def grade(text):
  text = text.lower()
  if any(w in text for w in ['senior', 'сеньор', 'сеньора', 'старший', 'старшего']):
    return 'senior'
  elif any(w in text for w in ['middle', 'мидл', 'миддл', 'мидла', 'миддла']):
    return 'middle'
  elif any(w in text for w in ['junior', 'джун', 'джуна', 'младший', 'младшего']):
    return 'junior'
  elif any(w in text for w in ['lead', 'team lead', 'teamlead', 'тимлид', 'тимлида']):
    return 'lead'
  else:
    return None

In [80]:
df_hh['grade'] = df_hh['text'].apply(grade)
df_hh['grade'].value_counts(dropna=False)

grade
None      3796
senior     204
junior     164
middle     101
lead        47
Name: count, dtype: int64

In [81]:
df_hh[df_hh['grade'].isna()]

,url,title,date,company,salary,experience,location,tags_raw,description,source,salary_from,salary_to,salary_mid,is_high_salary,text,grade
3888,https://hh.ru/vacancy/131586658,Заместитель генерального директора по строител...,2025-11-11 20:13:24,ОООГрант+,до 800 000 ₽ за месяц на руки,3–6 лет,NaN,"Производственное планирование, Оптимизация биз...","Обязанности: Организация, контроль и обеспечен...",hh_ru,800000.0,NaN,800000.0,True,Заместитель генерального директора по строител...,None
854,https://hh.ru/vacancy/131510357,Руководитель направления электронной коммерции,2026-02-19 10:15:52,ОООЭто Платежи,до 500 000 ₽ за месяц на руки,более 6 лет,NaN,"Управление командой, E-Commerce, Системный под...",О вакансии В связи с расширением деятельности ...,hh_ru,500000.0,NaN,500000.0,True,Руководитель направления электронной коммерции...,None
2899,https://hh.ru/vacancy/130601098,Руководитель проектов (реинжиниринг),2025-11-10 15:40:29,Diamond Personnel R&C,до 450 000 ₽ за месяц на руки,3–6 лет,NaN,Реинжиниринг бизнес-процессов,Обязанности: Управление проектами по реинжинир...,hh_ru,450000.0,NaN,450000.0,True,Руководитель проектов (реинжиниринг) Обязаннос...,None
2806,https://hh.ru/vacancy/131955166,Руководитель проекта на ТЭЦ,2025-12-04 17:19:21,A&M HUNT,до 400 000 ₽ за месяц на руки,3–6 лет,NaN,Основы управления проектами,Компания бизнес-партнер занимается проектирова...,hh_ru,400000.0,NaN,400000.0,True,Руководитель проекта на ТЭЦ Компания бизнес-па...,None
758,https://hh.ru/vacancy/131116730,Руководитель отдела ИТ,2026-03-23 14:46:17,ОООТорговый Дом Лотос,от 500 000 ₽ за месяц до вычета налогов,3–6 лет,NaN,"Информационные технологии, Информационная безо...",Обязанности: Внедрение технологий автоматизаци...,hh_ru,500000.0,NaN,500000.0,True,Руководитель отдела ИТ Обязанности: Внедрение ...,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1463,https://hh.ru/vacancy/131295754,Дизайнер сайтов на Tilda,2026-03-10 09:45:40,MAXVAL Marketing&Consulting,"от 55 000 до 70 000 ₽ за месяц , на руки",1–3 года,NaN,"Figma, Web-дизайн, UX, UI/UX, Adobe Photoshop,...",Обязанности: Корректировки сайтов на конструкт...,hh_ru,55000.0,70000.0,62500.0,False,Дизайнер сайтов на Tilda Обязанности: Корректи...,None
1464,https://hh.ru/vacancy/131297842,Дизайнер,2026-03-10 09:21:55,Prime Недвижимость,"от 80 000 до 100 000 ₽ за месяц , на руки",1–3 года,NaN,NaN,"Привет, меня зовут Аня, я руководитель отдела ...",hh_ru,80000.0,100000.0,90000.0,False,"Дизайнер Привет, меня зовут Аня, я руководител...",None
1465,https://hh.ru/vacancy/131298203,UX/UI-дизайнер,2026-03-10 08:30:23,Advline,"от 100 000 ₽ за месяц , до вычета налогов",3–6 лет,NaN,NaN,"Рекламное агентство ""Advline"" в поисках UX/UI-...",hh_ru,100000.0,NaN,100000.0,False,"UX/UI-дизайнер Рекламное агентство ""Advline"" в...",None
1466,https://hh.ru/vacancy/131299757,Дизайнер интерьеров,2026-03-10 08:14:01,ОООЗагородная Инвестиционная Компания,"от 150 000 ₽ за месяц , на руки",более 6 лет,NaN,"Дизайн интерьера, 3ds Max, Adobe Photoshop, 3D...",Обязанности: Разработка концепции и стиля инте...,hh_ru,150000.0,NaN,150000.0,False,Дизайнер интерьеров Обязанности: Разработка ко...,None
4311,https://hh.ru/vacancy/131656283,Специалист технической поддержки,2025-07-16 08:51:09,АОИнтернет Проекты,до 120 000 ₽ за месяц на руки,1–3 года,NaN,NaN,"Компания ""Интернет Проекты"" существует более 2...",hh_ru,120000.0,NaN,120000.0,False,"Специалист технической поддержки Компания ""Инт...",None

In [82]:
def work_format(text):
  text = text.lower()
  if any(w in text for w in ['удалён', 'удален', 'удалёнка', 'удаленка', 'remote']):
    return 'remote'
  elif any(w in text for w in ['гибрид', 'hybrid']):
    return 'hybrid'
  elif any(w in text for w in ['офис', 'очно', 'office']):
    return 'office'
  else:
    return None

In [83]:
df_hh['work_format'] = df_hh['text'].apply(work_format)
df_hh['work_format'].value_counts(dropna=False)

work_format
office    1517
remote    1452
None      1047
hybrid     296
Name: count, dtype: int64

In [84]:
df_hh = df_hh.dropna(subset=['work_format']).reset_index(drop=True)

In [85]:
tech_keywords = [
    'Python', 'JavaScript', 'TypeScript', 'Java', 'Go', 'Golang',
    'C++', 'C#', 'Rust', 'Kotlin', 'Swift', 'PHP', 'Ruby', 'Scala',
    'Matlab', 'Perl', 'Bash', 'Shell', 'PowerShell',
    'SQL', 'PostgreSQL', 'MySQL', 'MongoDB', 'Redis', 'Kafka',
    'ClickHouse', 'Cassandra', 'Elasticsearch', 'SQLite', 'Oracle',
    'MS SQL', 'MSSQL', 'MariaDB', 'DynamoDB', 'Redshift', 'BigQuery',
    'Snowflake', 'Greenplum', 'Vertica', 'Neo4j', 'RabbitMQ',
    'Pandas', 'NumPy', 'PyTorch', 'TensorFlow', 'Keras', 'Scikit-learn',
    'Spark', 'Airflow', 'dbt', 'Hadoop', 'Hive', 'Flink',
    'Machine Learning', 'Deep Learning', 'NLP', 'LLM', 'Data Science',
    'Computer Vision', 'MLOps', 'DataOps', 'BI', 'ETL', 'ELT',
    'XGBoost', 'CatBoost', 'LightGBM', 'BERT', 'GPT',
    'Django', 'FastAPI', 'Flask', 'Spring', 'SpringBoot',
    'Node.js', 'Express', 'NestJS', 'Laravel', 'Rails',
    'GraphQL', 'REST', 'gRPC', 'WebSocket', 'Celery',
    'React', 'Vue', 'Angular', 'Next.js', 'Nuxt', 'Svelte',
    'HTML', 'CSS', 'Webpack', 'Vite', 'Redux',
    'Docker', 'Kubernetes', 'Terraform', 'Ansible', 'Jenkins',
    'GitLab', 'GitHub', 'CI/CD', 'Linux', 'Nginx', 'Apache',
    'AWS', 'GCP', 'Azure', 'Yandex Cloud', 'VK Cloud',
    'Prometheus', 'Grafana', 'ELK', 'Kibana', 'Logstash',
    'Vault', 'Consul', 'Istio', 'Helm', 'ArgoCD',
    'Tableau', 'Power BI', 'PowerBI', 'Superset', 'Metabase',
    'Looker', 'QlikView', 'Excel', 'Google Sheets',
    '1С', 'SAP', 'Jira', 'Confluence',
    'Android', 'iOS', 'React Native', 'Flutter', 'Xamarin',
    'Selenium', 'Pytest', 'JUnit', 'Postman', 'JMeter',
    'Cypress', 'Playwright', 'Appium', 'TestRail',
    'Git', 'Linux', 'Agile', 'Scrum', 'Kanban',
    'Microservices', 'API', 'S3', 'gRPC'
    ]

In [86]:
def technologies(text):
  found = []
  text_lower = text.lower()
  for tech in tech_keywords:
    tech_lower = tech.lower()
    if tech_lower in text_lower:
      found.append(tech)
  return ', '.join(found) if found else None

In [87]:
df_hh['technologies'] = df_hh['text'].apply(technologies)
df_hh

,url,title,date,company,salary,experience,location,tags_raw,description,source,salary_from,salary_to,salary_mid,is_high_salary,text,grade,work_format,technologies
0,https://hh.ru/vacancy/131510357,Руководитель направления электронной коммерции,2026-02-19 10:15:52,ОООЭто Платежи,до 500 000 ₽ за месяц на руки,более 6 лет,NaN,"Управление командой, E-Commerce, Системный под...",О вакансии В связи с расширением деятельности ...,hh_ru,500000.0,NaN,500000.0,True,Руководитель направления электронной коммерции...,None,office,None
1,https://hh.ru/vacancy/130601098,Руководитель проектов (реинжиниринг),2025-11-10 15:40:29,Diamond Personnel R&C,до 450 000 ₽ за месяц на руки,3–6 лет,NaN,Реинжиниринг бизнес-процессов,Обязанности: Управление проектами по реинжинир...,hh_ru,450000.0,NaN,450000.0,True,Руководитель проектов (реинжиниринг) Обязаннос...,None,office,Excel
2,https://hh.ru/vacancy/131576330,Lead AI R&D Engineer,2026-02-02 13:47:19,ОООМК Групп,от 500 000 ₽ за месяц на руки,3–6 лет,NaN,"Python, Разработка нового продукта",В Инссмарт мы строим не очередную “AI-инициати...,hh_ru,500000.0,NaN,500000.0,True,Lead AI R&D Engineer В Инссмарт мы строим не о...,senior,hybrid,"Python, LLM, BI, GPT, API"
3,https://hh.ru/vacancy/131116730,Руководитель отдела ИТ,2026-03-23 14:46:17,ОООТорговый Дом Лотос,от 500 000 ₽ за месяц до вычета налогов,3–6 лет,NaN,"Информационные технологии, Информационная безо...",Обязанности: Внедрение технологий автоматизаци...,hh_ru,500000.0,NaN,500000.0,True,Руководитель отдела ИТ Обязанности: Внедрение ...,None,office,None
4,https://hh.ru/vacancy/131878416,Руководитель направления информационной безопа...,2025-11-24 12:32:18,Qugo,до 400 000 ₽ за месяц до вычета налогов,3–6 лет,NaN,NaN,"Мы ищем: Практичного руководителя, готового уп...",hh_ru,400000.0,NaN,400000.0,True,Руководитель направления информационной безопа...,None,remote,"Python, Bash, Linux, Linux"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3260,https://hh.ru/vacancy/131295754,Дизайнер сайтов на Tilda,2026-03-10 09:45:40,MAXVAL Marketing&Consulting,"от 55 000 до 70 000 ₽ за месяц , на руки",1–3 года,NaN,"Figma, Web-дизайн, UX, UI/UX, Adobe Photoshop,...",Обязанности: Корректировки сайтов на конструкт...,hh_ru,55000.0,70000.0,62500.0,False,Дизайнер сайтов на Tilda Обязанности: Корректи...,None,office,None
3261,https://hh.ru/vacancy/131297842,Дизайнер,2026-03-10 09:21:55,Prime Недвижимость,"от 80 000 до 100 000 ₽ за месяц , на руки",1–3 года,NaN,NaN,"Привет, меня зовут Аня, я руководитель отдела ...",hh_ru,80000.0,100000.0,90000.0,False,"Дизайнер Привет, меня зовут Аня, я руководител...",None,office,None
3262,https://hh.ru/vacancy/131298203,UX/UI-дизайнер,2026-03-10 08:30:23,Advline,"от 100 000 ₽ за месяц , до вычета налогов",3–6 лет,NaN,NaN,"Рекламное агентство ""Advline"" в поисках UX/UI-...",hh_ru,100000.0,NaN,100000.0,False,"UX/UI-дизайнер Рекламное агентство ""Advline"" в...",None,remote,CSS
3263,https://hh.ru/vacancy/131299757,Дизайнер интерьеров,2026-03-10 08:14:01,ОООЗагородная Инвестиционная Компания,"от 150 000 ₽ за месяц , на руки",более 6 лет,NaN,"Дизайн интерьера, 3ds Max, Adobe Photoshop, 3D...",Обязанности: Разработка концепции и стиля инте...,hh_ru,150000.0,NaN,150000.0,False,Дизайнер интерьеров Обязанности: Разработка ко...,None,remote,Excel
3264,https://hh.ru/vacancy/131656283,Специалист технической поддержки,2025-07-16 08:51:09,АОИнтернет Проекты,до 120 000 ₽ за месяц на руки,1–3 года,NaN,NaN,"Компания ""Интернет Проекты"" существует более 2...",hh_ru,120000.0,NaN,120000.0,False,"Специалист технической поддержки Компания ""Инт...",None,hybrid,"SQL, HTML, API"

In [88]:
df_hh['technologies'].isna().sum()

np.int64(1311)

In [89]:
df_hh = df_hh.dropna(subset=['technologies']).reset_index(drop=True)
len(df_hh)

1954

In [90]:
def specialization(text):
  text = text.lower()
  if any(w in text for w in ['data engineer', 'дата инженер', 'etl-разработчик']):
    return 'Data Engineer'
  elif any(w in text for w in ['бизнес-аналитик', 'бизнес аналитик', 'business analyst']):
    return 'Business Analyst'
  elif any(w in text for w in ['продуктовый аналитик', 'product analyst', 'маркетинговый аналитик']):
    return 'Product Analyst'
  elif any(w in text for w in ['data analyst', 'data analytics', 'аналитик данных', 'analyst', 'head of data']):
    return 'Data Analyst'
  elif any(w in text for w in ['data scientist', 'data science', 'датасаентист', 'дата саентист']):
    return 'Data Scientist'
  elif any(w in text for w in ['ml engineer', 'machine learning engineer', 'mle', 'mlops', 'ml-инженер', 'ml инженер',
                               'ml разработчик', 'мл инженер', 'мл-инженер', 'мл разработчик']):
    return 'ML Engineer'
  elif any(w in text for w in ['nlp', 'llm', 'computer vision', 'cv engineer', 'нлп', 'ллм', 'компьютерное зрение']):
    return 'AI/NLP Engineer'
  elif any(w in text for w in ['системный аналитик', 'system analyst']):
    return 'System Analyst'
  elif any(w in text for w in ['devops', 'девелопер', 'девопс', 'sre', 'site reliability', 'platform engineer']):
    return 'DevOps/SRE'
  elif any(w in text for w in ['fullstack', 'full stack', 'фулстек', 'full-stack']):
    return 'Fullstack Developer'
  elif any(w in text for w in ['frontend', 'фронтенд', 'front-end', 'front end', 'фронт']):
    return 'Frontend Developer'
  elif any(w in text for w in ['backend', 'бэкенд', 'бекенд', 'back-end', 'back end', 'python разработчик',
                               'python developer', 'java developer', 'java разработчик', 'go разработчик',
                               'go developer', 'php разработчик', 'fastapi developer', 'python/fastapi',
                               'senior python', 'django', 'python/django', 'go разработчик', 'golang разработчик', 'crypto']):
    return 'Backend Developer'
  elif any(w in text for w in ['mobile', 'android', 'ios разработчик', 'ios developer', 'flutter', 'мобильный разработчик']):
    return 'Mobile Developer'
  elif any(w in text for w in ['unity', 'unreal', 'game developer', 'gamedev', 'геймдев', 'юнити']):
    return 'Game Developer'
  elif any(w in text for w in ['qa', 'тестировщик', 'test engineer', 'quality assurance', 'автоматизатор']):
    return 'QA Engineer'
  elif any(w in text for w in ['security', 'информационная безопасность', 'кибербезопасность',
                               'инфбез', 'пентест', 'pentest']):
    return 'Security Engineer'
  elif any(w in text for w in ['архитектор', 'architect', 'solution architect']):
    return 'Architect'
  elif any(w in text for w in ['team lead', 'teamlead', 'тимлид', 'tech lead', 'техлид', 'engineering manager', 'руководитель разработки']):
    return 'Tech Lead/Manager'
  elif any(w in text for w in ['1с программист', '1с разработчик', '1с аналитик']):
    return '1C Developer'
  elif any(w in text for w in ['scrum master', 'agile coach', 'project manager', 'проджект менеджер', 'менеджер проекта']):
    return 'Project/Scrum Manager'
  elif any(w in text for w in ['ux', 'ui', 'дизайнер', 'product designer']):
    return 'UX/UI Designer'
  else:
    return None

In [91]:
df_hh['specialization'] = df_hh['text'].apply(specialization)
df_hh['specialization'].value_counts(dropna=False)

specialization
None                     753
UX/UI Designer           426
Business Analyst         110
DevOps/SRE               108
System Analyst            73
QA Engineer               63
AI/NLP Engineer           55
Project/Scrum Manager     55
Mobile Developer          52
Data Analyst              43
Frontend Developer        32
Security Engineer         28
ML Engineer               26
Game Developer            26
Architect                 25
Data Scientist            24
Backend Developer         20
Data Engineer             19
Fullstack Developer       10
Tech Lead/Manager          5
1C Developer               1
Name: count, dtype: int64

In [92]:
df_hh = df_hh.dropna(subset=['specialization']).reset_index(drop=True)
len(df_hh)

1201

In [93]:
df_hh

,url,title,date,company,salary,experience,location,tags_raw,description,source,salary_from,salary_to,salary_mid,is_high_salary,text,grade,work_format,technologies,specialization
0,https://hh.ru/vacancy/131576330,Lead AI R&D Engineer,2026-02-02 13:47:19,ОООМК Групп,от 500 000 ₽ за месяц на руки,3–6 лет,NaN,"Python, Разработка нового продукта",В Инссмарт мы строим не очередную “AI-инициати...,hh_ru,500000.0,NaN,500000.0,True,Lead AI R&D Engineer В Инссмарт мы строим не о...,senior,hybrid,"Python, LLM, BI, GPT, API",AI/NLP Engineer
1,https://hh.ru/vacancy/131878416,Руководитель направления информационной безопа...,2025-11-24 12:32:18,Qugo,до 400 000 ₽ за месяц до вычета налогов,3–6 лет,NaN,NaN,"Мы ищем: Практичного руководителя, готового уп...",hh_ru,400000.0,NaN,400000.0,True,Руководитель направления информационной безопа...,None,remote,"Python, Bash, Linux, Linux",DevOps/SRE
2,https://hh.ru/vacancy/131658437,DevOps,2026-03-06 20:30:35,YCLIENTS LLC,до 400 000 ₽ за месяц на руки,1–3 года,NaN,"Kubernetes, CI/CD, DevOps",Несколько лет назад YCLIENTS был амбициозным с...,hh_ru,400000.0,NaN,400000.0,True,DevOps Несколько лет назад YCLIENTS был амбици...,None,hybrid,"SQL, PostgreSQL, MySQL, Redis, Kafka, ClickHou...",DevOps/SRE
3,https://hh.ru/vacancy/131625963,Senior Site Reliability Engineer (SRE),2025-08-19 19:53:33,TravelLine,до 500 000 ₽ за месяц на руки,более 6 лет,NaN,"Prometheus, Grafana, ELK, MS SQL, PostgreSQL, ...",В TravelLine мы разрабатываем единую функциона...,hh_ru,500000.0,NaN,500000.0,True,Senior Site Reliability Engineer (SRE) В Trave...,senior,remote,"SQL, PostgreSQL, Redis, MS SQL, BI, Docker, Ku...",DevOps/SRE
4,https://hh.ru/vacancy/131132127,Senior ML Engineer (Generative AI),2026-03-19 10:21:15,LionAdverts,от 450 000 до 700 000 ₽ за месяц на руки,3–6 лет,NaN,"Stable Diffusion, SDXL, ComfyUI, ML, Python, Н...",О проекте: Мы создаём систему интерактивных ИИ...,hh_ru,450000.0,700000.0,575000.0,True,Senior ML Engineer (Generative AI) О проекте: ...,senior,remote,"Python, PyTorch, API",ML Engineer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1196,https://hh.ru/vacancy/131271684,Дизайнер,2026-03-12 11:27:01,ИПФедорченко ОВ,"от 80 000 ₽ за месяц , на руки",1–3 года,NaN,NaN,«OLEXDECO» ™ один из наиболее динамично развив...,hh_ru,80000.0,NaN,80000.0,False,Дизайнер «OLEXDECO» ™ один из наиболее динамич...,None,office,Git,UX/UI Designer
1197,https://hh.ru/vacancy/131273338,Графический дизайнер + СММ (специалист по марк...,2026-03-11 20:02:15,ОООИнновационный Завод Легких Конструкций Рус,"150 000 ₽ за месяц , на руки",1–3 года,NaN,NaN,Мы - активно развивающаяся группа компаний (на...,hh_ru,150000.0,NaN,150000.0,False,Графический дизайнер + СММ (специалист по марк...,None,remote,Git,UX/UI Designer
1198,https://hh.ru/vacancy/131291149,Product Manager мобильных приложений,2026-03-10 16:18:54,Broad Apps,"от 150 000 ₽ за месяц , до вычета налогов",1–3 года,NaN,"A/B тесты, Unit-экономика, iOS, User Flow, Моб...","Приветствую тебя, уважаемый кандидат! Мы — Bro...",hh_ru,150000.0,NaN,150000.0,False,Product Manager мобильных приложений Приветств...,None,remote,"Go, BI, iOS",Mobile Developer
1199,https://hh.ru/vacancy/131298203,UX/UI-дизайнер,2026-03-10 08:30:23,Advline,"от 100 000 ₽ за месяц , до вычета налогов",3–6 лет,NaN,NaN,"Рекламное агентство ""Advline"" в поисках UX/UI-...",hh_ru,100000.0,NaN,100000.0,False,"UX/UI-дизайнер Рекламное агентство ""Advline"" в...",None,remote,CSS,UX/UI Designer
1200,https://hh.ru/vacancy/131299757,Дизайнер интерьеров,2026-03-10 08:14:01,ОООЗагородная Инвестиционная Компания,"от 150 000 ₽ за месяц , на руки",более 6 лет,NaN,"Дизайн интерьера, 3ds Max, Adobe Photoshop, 3D...",Обязанности: Разработка концепции и стиля инте...,hh_ru,150000.0,NaN,150000.0,False,Дизайнер интерьеров Обязанности: Разработка ко...,None,remote,Excel,UX/UI Designer

In [94]:
df_hh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1201 entries, 0 to 1200
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   url             1201 non-null   object
 1   title           1201 non-null   object
 2   date            1201 non-null   object
 3   company         1200 non-null   object
 4   salary          1201 non-null   object
 5   experience      1201 non-null   object
 6   location        0 non-null      float64
 7   tags_raw        847 non-null    object
 8   description     1201 non-null   object
 9   source          1201 non-null   object
 10  salary_from     1201 non-null   float64
 11  salary_to       443 non-null    float64
 12  salary_mid      1201 non-null   float64
 13  is_high_salary  1201 non-null   bool
 14  text            1201 non-null   object
 15  grade           248 non-null    object
 16  work_format     1201 non-null   object
 17  technologies    1201 non-null   object
 18  specialization  1201 non-null   object
dtypes: bool(1), float64(4), object(14)
memory usage: 170.2+ KB

In [95]:
df_hh.to_csv('df_hh.csv')